[project]
name = "articlemakeragent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "requests>=2.32.5",
    "selenium>=4.38.0",
    "tenacity>=9.1.2",
]
